server: 
  port: 8101 
  max-http-header-size: 1024000 
spring: 
  application:
    name: barry-gateway-service
  cloud:
    gateway:
      globalcors: 
        corsConfigurations: #配置跨域
          '[/**]': 
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      loadbalancer: 
        use404: true #//找不到服务返回404，默认是503
      discovery:
        locator:
          enabled: true #开启与服务注册于发现组件进行结合
          lowerCaseServiceId: true #开启微服务名称小写
      #routes:
       # - id: cms-service
        #  uri: lb://cms-service
         # order: 10000
          #predicates:
           # - Path=/cms-service/**
eureka: 
  instance: 
    instance-id: ${spring.application.name}:${random.uuid}
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 
    registry-fetch-interval-seconds: 10 #从注册中心获取注册服务的频率，单位为秒 
    eureka-service-url-poll-interval-seconds: 100 #轮询注册中心的服务频率，单位秒
management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:  
    web:
      exposure: 
        include: "*"
use: 
  format: 
    response: false